require "stimulus/manifest"
require "rake/extensions"
require "rails/generators"
require "rails/generators/rails/app/app_generator"

module Stimulus
  module Tasks
    extend self

    def detect_install_template(root)
      if root.join("config/importmap.rb").exist?
        "importmap"
      elsif root.join("package.json").exist?
        if root.join("bun.config.js").exist?
          "bun"
        else
          "node"
        end
      end
    end

    def self.run_stimulus_install_template(path, root)
      Rails::Generators::AppGenerator.apply_rails_template(File.expand_path("../install/#{path}.rb", __dir__), root)
    end

  end
end

namespace :stimulus do
  desc "Install Stimulus into the app"
  task :install do
    if (install_template = Stimulus::Tasks.detect_install_template(Rails.root))
      Stimulus::Tasks.run_stimulus_install_template("stimulus_with_#{install_template}", Rails.root)
    else
      puts "You must either be running with node (package.json) or importmap-rails (config/importmap.rb) to use this gem."
    end
  end

  namespace :install do
    desc "Install Stimulus in an app running importmap-rails"
    task :importmap do
      Stimulus::Tasks.run_stimulus_install_template("stimulus_with_importmap", Rails.root)
    end

    desc "Install Stimulus in an app running node"
    task :node do
      Stimulus::Tasks.run_stimulus_install_template("stimulus_with_node", Rails.root)
    end

    desc "Install Stimulus in an app running bun"
    task :bun do
      Stimulus::Tasks.run_stimulus_install_template("stimulus_with_bun", Rails.root)
    end
  end

  namespace :manifest do
    desc "Show the current Stimulus manifest (all installed controllers)"
    task :display do
      puts Stimulus::Manifest.generate_from(Rails.root.join("app/javascript/controllers"))
    end

    desc "Update the Stimulus manifest (will overwrite controllers/index.js)"
    task :update do
      manifest = Stimulus::Manifest.generate_from(Rails.root.join("app/javascript/controllers"))

      File.open(Rails.root.join("app/javascript/controllers/index.js"), "w+") do |index|
        index.puts "// This file is auto-generated by ./bin/rails stimulus:manifest:update"
        index.puts "// Run that command whenever you add a new controller or create them with"
        index.puts "// ./bin/rails generate stimulus controllerName"
        index.puts
        index.puts %(import { application } from "./application")
        index.puts manifest
      end
    end
  end
end

if defined?(ENGINE_ROOT) && (engine = Rails::Engine.find(ENGINE_ROOT))
  unscoped do
    namespace :stimulus do

      desc "Install Stimulus into the engine"
      task :install do
        if (install_template = Stimulus::Tasks.detect_install_template(engine.root))
          Stimulus::Tasks.run_stimulus_install_template("stimulus_with_#{install_template}", engine.root)
        else
          puts "You must either be running with node/bun (package.json) or importmap-rails (config/importmap.rb) to use this gem."
        end
      end

      namespace :install do
        desc "Install Stimulus in an engine running importmap-rails"
        task :importmap do
          Stimulus::Tasks.run_stimulus_install_template("stimulus_with_importmap", Rails.root)
        end

        desc "Install Stimulus in an engine running node"
        task :node do
          Stimulus::Tasks.run_stimulus_install_template("stimulus_with_node", Rails.root)
        end

        desc "Install Stimulus in an engine running bun"
        task :bun do
          Stimulus::Tasks.run_stimulus_install_template("stimulus_with_bun", Rails.root)
        end
      end

      namespace :manifest do

        desc "Show the current engine Stimulus manifest (all installed controllers)"
        task :display do
          puts Stimulus::Manifest.generate_from(engine.root.join("app/javascript/controllers"))
        end

        desc "Update the engine Stimulus manifest (will overwrite controllers/index.js)"
        task :update do
          manifest = Stimulus::Manifest.generate_from(engine.root.join("app/javascript/controllers"))
          File.open(engine.root.join("app/javascript/controllers/index.js"), "w+") do |index|
            index.puts "// This file is auto-generated by ./bin/rails stimulus:manifest:update"
            index.puts "// Run that command whenever you add a new controller or create them with"
            index.puts "// ./bin/rails generate stimulus controllerName"
            index.puts
            index.puts %(import { application } from "./application")
            index.puts manifest
          end
        end

      end
    end
  end
end
